export const courses = [
  {
    id: 1,
    title: "Certificate Course in Structured Query Language using MySQL",
    description: "Learn the fundamentals of SQL and how to manage databases effectively.",
    category: "SQL",
    price: 0,
    isFree: true,
    imageUrl: null,
  },
  {
    id: 2,
    title: "Introduction to Python",
    description: "Get started with Python programming, covering basic concepts and practical applications.",
    category: "Python",
    price: 0,
    isFree: true,
    imageUrl: null,
  },
  {
    id: 3,
    title: "Certificate Course in Basic Python",
    description: "A comprehensive course to build your Python skills from scratch.",
    category: "Python",
    price: 0,
    isFree: true,
    imageUrl: null,
  },
  {
    id: 4,
    title: "Advanced Program in Cyber Security",
    description: "Deep dive into advanced concepts in Cyber Security and threat management.",
    category: "Cyber Security",
    price: 4500,
    isFree: false,
    imageUrl: null,
  },
  {
    id: 5,
    title: "Certificate Course in Linux Server Administration",
    description: "Gain expertise in Linux server management and administration.",
    category: "Linux",
    price: 850,
    isFree: false,
    imageUrl: null,
  },
  {
    id: 6,
    title: "Certificate Course in Cyber Security",
    description: "Understand the principles of Cyber Security and how to implement them effectively.",
    category: "Cyber Security",
    price: 1550,
    isFree: false,
    imageUrl: null,
  },
  {
    id: 7,
    title: "AWS Certification Course",
    description: "Master Amazon Web Services and get certified in cloud computing and cloud architecture.",
    category: "AWS",
    price: 950,
    isFree: false,
    imageUrl: null,
  },
  {
    id: 8,
    title: "HTML Certification Course",
    description: "Learn HTML, the foundational language of web development, and get certified in building websites.",
    category: "Web Development",
    price: 0,
    isFree: true,
    imageUrl: null,
  },
  {
    id: 9,
    title: "Javascript Certification Course",
    description: "Become proficient in JavaScript programming and enhance your web development skills.",
    category: "Web Development",
    price: 0,
    isFree: true,
    imageUrl: null,
  },
  {
    id: 10,
    title: "Basic AI Certification Course",
    description: "Learn the basics of Artificial Intelligence and its applications in the real world.",
    category: "AI",
    price: 0,
    isFree: true,
    imageUrl: null,
  },
  {
    id: 11,
    title: "ReactJS Certification Course",
    description: "Master ReactJS to build interactive user interfaces and dynamic web applications.",
    category: "Web Development",
    price: 0,
    isFree: true,
    imageUrl: null,
  },
  {
    id: 12,
    title: "NodeJS Certification Course",
    description: "Learn how to build server-side applications using Node.js, a powerful backend framework.",
    category: "Web Development",
    price: 0,
    isFree: true,
    imageUrl: null,
  },
  {
    id: 13,
    title: "React Native Certification Course",
    description: "Get certified in building cross-platform mobile applications using React Native.",
    category: "Mobile Development",
    price: 650,
    isFree: false,
    imageUrl: null,
  },
  {
    id: 14,
    title: "AngularJS Certification Course",
    description: "Learn AngularJS to create dynamic, single-page applications with ease.",
    category: "Web Development",
    price: 0,
    isFree: true,
    imageUrl: null,
  },
  {
    id: 15,
    title: "TypeScript Certification Course",
    description: "Understand the power of TypeScript to write clean, maintainable, and scalable JavaScript applications.",
    category: "Web Development",
    price: 0,
    isFree: true,
    imageUrl: null,
  },
  {
    id: 16,
    title: "C Program Certification Course",
    description: "Master the C programming language and become proficient in developing software applications and system-level programming.",
    category: "Programming",
    price: 0,
    isFree: true,
    imageUrl: null,
  },
];
